
SRC = main.c scanner.c token_buffer.c parser.c first_phase.c semantic.c semantic_list.c precedence.c precedence_stack.c precedence_tree.c symtable.c generate.c gen_handler.c
OUT = ifj24
CC = gcc

build: $(SRC)
	$(CC) -o $(OUT) $(SRC)
